module

public import Coxeter.Basic
public import Mathlib.GroupTheory.PresentedGroup

/-!
# The Artin (braid) group of a Coxeter system

The Artin (braid) group is the group
generated by the simple reflections of a Coxeter system
quotiented by the braid relations, but *not* the quadratic relations `s_i^2 = 1`.

The natural quotient map is `quot : BraidGroup W →* W`.

Assuming `Matsumoto W` there is a well-defined lift
`existsUnique_braidLift` of `w : W` back into `BraidGroup W`,
via any reduced word for `w`.

## Main definitions

* `Coxeter.BraidGroup`, `Coxeter.quot`
* `Coxeter.existsUnique_braidLift`
-/

@[expose] public section

namespace Coxeter

open List CoxeterSystem CoxeterGroup

variable {W : Type*} [CoxeterGroup W]

section ArtinBraid

/-! ### The Artin (braid) group, and the lift `W → BraidGroup W` -/

/-- The defining relations of the Artin (braid) group attached to a Coxeter system:
for each pair of simple reflections `i i'`, the two braid words
`s_i s_{i'} s_i ⋯` and `s_{i'} s_i s_{i'} ⋯` (`M i i'` letters each) become equal. -/
def braidGroupRels (W : Type*) [CoxeterGroup W] : Set (FreeGroup (B W)) :=
  {r | ∃ i i' : B W,
    r = ((braidWord M i i').map FreeGroup.of).prod
      * (((braidWord M i' i).map FreeGroup.of).prod)⁻¹}

/-- The **Artin (braid) group** of a Coxeter system
generators `B W`, modulo only the braid relations. -/
abbrev BraidGroup (W : Type*) [CoxeterGroup W] : Type _ := PresentedGroup (braidGroupRels W)

/-- The group homomorphism collapsing `BraidGroup W` back onto `W`
sending each generator to the corresponding simple reflection. -/
def quot {W : Type*} [CoxeterGroup W] : BraidGroup W →* W :=
  PresentedGroup.toGroup (f := fun i => cs.simple i) (by
    rintro r ⟨i, i', rfl⟩
    simp only [map_mul, map_inv, mul_inv_eq_one]
    rw [map_list_prod, map_list_prod, List.map_map, List.map_map]
    have : ((braidWord M i i').map (FreeGroup.lift (fun i => cs.simple i) ∘ FreeGroup.of)).prod
        = cs.wordProd (braidWord M i i') := by
      congr 1
      apply List.map_congr_left
      intro j _
      exact FreeGroup.lift_apply_of
    rw [this]
    have : ((braidWord M i' i).map (FreeGroup.lift (fun i => cs.simple i) ∘ FreeGroup.of)).prod
        = cs.wordProd (braidWord M i' i) := by
      congr 1
      apply List.map_congr_left
      intro j _
      exact FreeGroup.lift_apply_of
    rw [this]
    exact cs.wordProd_braidWord_eq i i')

end ArtinBraid

section LiftQuot

/-- The naive lift of a word to `BraidGroup W`, sending each letter to its generator. -/
def braidLift {W : Type*} [CoxeterGroup W] (ω : List (B W)) : BraidGroup W :=
  (ω.map (PresentedGroup.of (rels := braidGroupRels W))).prod

private theorem braidLift_eq_mk {W : Type*} [CoxeterGroup W] (l : List (B W)) :
    braidLift l = PresentedGroup.mk (braidGroupRels W) ((l.map FreeGroup.of).prod) := by
  simp only [braidLift, map_list_prod, List.map_map]
  rfl

private theorem braidLift_append {W : Type*} [CoxeterGroup W] (l1 l2 : List (B W)) :
    braidLift (W := W) (l1 ++ l2) = braidLift l1 * braidLift l2 := by
  simp [braidLift, List.map_append, List.prod_append]

private theorem quot_braidLift {W : Type*} [CoxeterGroup W] (ω : List (B W)) :
    quot (braidLift ω) = cs.wordProd ω := by
  unfold braidLift quot wordProd
  rw [map_list_prod, List.map_map]
  congr 1
  apply List.map_congr_left
  intro i _
  exact PresentedGroup.toGroup.of _

private theorem braidLift_of_braidMove {ω ω' : List (B W)} (h : BraidMove ω ω') :
    braidLift ω = braidLift ω' := by
  obtain ⟨i, i', α, β, hω, hω'⟩ := h
  have hrel : ((braidWord M i i').map FreeGroup.of).prod
      * (((braidWord M i' i).map FreeGroup.of).prod)⁻¹ ∈ braidGroupRels W := ⟨i, i', rfl⟩
  have hmid : braidLift (braidWord M i i') = braidLift (braidWord M i' i) := by
    rw [braidLift_eq_mk, braidLift_eq_mk]
    exact PresentedGroup.mk_eq_mk_of_mul_inv_mem hrel
  rw [hω, hω', braidLift_append, braidLift_append, braidLift_append, braidLift_append, hmid]

private theorem braidLift_of_eqvGen {ω ω' : List (B W)} (h : Relation.EqvGen BraidMove ω ω') :
    braidLift ω = braidLift ω' := by
  induction h with
  | rel a b hab => exact braidLift_of_braidMove hab
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih1 ih2 => exact ih1.trans ih2

/-- **The set of candidate values is a singleton**
The image of a reduced word for `w` under
`braidLift` doesn't depend on which reduced word was chosen. -/
theorem existsUnique_braidLift [Matsumoto W] (w : W) :
    ∃! x : BraidGroup W,
      ∃ ω : ReducedWord w, x = braidLift ω.val ∧ quot x = w
  := by
  obtain ⟨ω⟩ : Nonempty (ReducedWord w) := inferInstance
  refine ⟨braidLift ω.val, ⟨ω, rfl, by rw [quot_braidLift, ω.wordProd_eq]⟩, ?_⟩
  rintro x ⟨ω', rfl, -⟩
  exact braidLift_of_eqvGen (Matsumoto.reduced_words_convert w ω' ω)

end LiftQuot

end Coxeter
