module

public import Coxeter.StrongExchange

/-!
# Dihedral parabolic subgroups

This file studies the rank-two (dihedral) parabolic subgroup generated by two simple reflections,
and minimal-length right coset representatives for it.

## Main definitions

* `Coxeter.rankTwoSubgroup`

## Main statements

* `Coxeter.exists_confined_reduced_word`
* `Coxeter.exists_minimal_rightCosetRep`
* `Coxeter.mem_alternatingWord`
-/

@[expose] public section

namespace Coxeter

open List CoxeterSystem CoxeterGroup

variable {W : Type*} [CoxeterGroup W]

/-- The rank-2 parabolic subgroup generated by two simple reflections. -/
def rankTwoSubgroup (i i' : B W) : Subgroup W := Subgroup.closure {cs.simple i, cs.simple i'}

/-- Every element of `rankTwoSubgroup i i'`
can be written as `cs.wordProd μ` for some
(not necessarily reduced) word `μ`
using only the letters `i`, `i'`. -/
private theorem exists_confined_word
  {i i' : B W} {v : W}
  (hv : v ∈ rankTwoSubgroup i i') :
  ∃ μ : List (B W),
    v = cs.wordProd μ ∧ ∀ k ∈ μ, k = i ∨ k = i' := by
  induction hv using Subgroup.closure_induction with
  | mem x hx =>
      rcases hx with h | h
      · exact ⟨[i], by rw [wordProd_singleton, h], by simp⟩
      · exact ⟨[i'], by rw [wordProd_singleton, h], by simp⟩
  | one => exact ⟨[], by rw [wordProd_nil], by simp⟩
  | mul x y _ _ ihx ihy =>
      obtain ⟨μx, hμx1, hμx2⟩ := ihx
      obtain ⟨μy, hμy1, hμy2⟩ := ihy
      refine ⟨μx ++ μy, ?_, ?_⟩
      · rw [wordProd_append, ← hμx1, ← hμy1]
      · intro k hk
        rcases List.mem_append.mp hk with hk | hk
        · exact hμx2 k hk
        · exact hμy2 k hk
  | inv x _ ihx =>
      obtain ⟨μ, hμ1, hμ2⟩ := ihx
      refine ⟨μ.reverse, ?_, ?_⟩
      · rw [hμ1, wordProd_reverse]
      · intro k hk
        exact hμ2 k (List.mem_reverse.mp hk)

/-- Every element of `rankTwoSubgroup i i'`
has a **reduced** word using only the letters
`i`, `i'`. -/
theorem exists_confined_reduced_word
  {i i' : B W} {v : W}
  (hv : v ∈ rankTwoSubgroup i i') :
  ∃ μ : List (B W),
    cs.IsReduced μ ∧ v = cs.wordProd μ ∧ ∀ k ∈ μ, k = i ∨ k = i' := by
  obtain ⟨μ₀, hμ₀1, hμ₀2⟩ := exists_confined_word hv
  obtain ⟨μ, hsub, hred, heq⟩ := exists_reduced_subword μ₀
  exact ⟨μ, hred, hμ₀1.trans heq, fun k hk => hμ₀2 k (hsub.subset hk)⟩

/-- Every `w : W` factors as `w = w₀ * v` with `v ∈ rankTwoSubgroup i i'` and `w₀` having no right
descent among `i`, `i'` (i.e. `w₀` is of minimal length in the coset `w₀ * rankTwoSubgroup i i'`).
Obtained by repeatedly cancelling a right descent among `i`, `i'` off the right of `w`, which
strictly decreases length and so terminates. -/
theorem exists_minimal_rightCosetRep (i i' : B W) (w : W) :
    ∃ w₀ v, v ∈ rankTwoSubgroup i i' ∧ w = w₀ * v ∧
      ¬ cs.IsRightDescent w₀ i ∧ ¬ cs.IsRightDescent w₀ i' := by
  induction hn : cs.length w using Nat.strong_induction_on generalizing w with
  | _ n ih =>
    subst hn
    by_cases hi : cs.IsRightDescent w i
    · obtain ⟨w₀, v, hv, hw, hi0, hi'0⟩ :=
        ih (cs.length (w * cs.simple i)) hi (w * cs.simple i) rfl
      refine ⟨w₀, v * cs.simple i, Subgroup.mul_mem _ hv (Subgroup.subset_closure (Or.inl rfl)),
        ?_, hi0, hi'0⟩
      rw [← mul_assoc, ← hw, cs.simple_mul_simple_cancel_right]
    · by_cases hi' : cs.IsRightDescent w i'
      · obtain ⟨w₀, v, hv, hw, hi0, hi'0⟩ :=
          ih (cs.length (w * cs.simple i')) hi' (w * cs.simple i') rfl
        refine ⟨w₀, v * cs.simple i', Subgroup.mul_mem _ hv (Subgroup.subset_closure (Or.inr rfl)),
          ?_, hi0, hi'0⟩
        rw [← mul_assoc, ← hw, cs.simple_mul_simple_cancel_right]
      · exact ⟨w, 1, Subgroup.one_mem _, (mul_one w).symm, hi, hi'⟩

/-- The easy half of the "gate property" (see `DihedralSubProperties` in `Coxeter/Hecke.lean`): if
`v` has a right descent at `j` and `w * v` has no length cancellation (`hlen`), then `w * v` has a
right descent at `j` too. General (no `rankTwoSubgroup` hypothesis needed), following directly from
`isRightInversion_of_isRightInversion_mul_right`. The converse ("hard half": `w * v` having a
descent at `j` forces `v` to) is what's still deferred, since it needs `hlen` itself established
from `w`/`v`'s descents rather than assumed outright. -/
theorem isRightDescent_mul_right_of_isRightDescent {w v : W}
    (hlen : cs.length (w * v) = cs.length w + cs.length v) {j : B W}
    (hj : cs.IsRightDescent v j) : cs.IsRightDescent (w * v) j := by
  rw [← isRightInversion_simple_iff_isRightDescent] at hj ⊢
  exact isRightInversion_of_isRightInversion_mul_right hj hlen

/-- Every letter of `alternatingWord i i' p` is `i` or `i'`. -/
theorem mem_alternatingWord {i i' k : B W} {p : ℕ} (hk : k ∈ alternatingWord i i' p) :
    k = i ∨ k = i' := by
  obtain ⟨n, hn, rfl⟩ := List.mem_iff_getElem.mp hk
  rw [length_alternatingWord] at hn
  rw [getElem_alternatingWord i i' p n hn]
  split <;> simp

/-- A reduced word can never repeat a letter in two consecutive positions: `s_k * s_k = 1` would
let the pair cancel, giving a strictly shorter word for the same element. -/
private theorem not_isReduced_append_simple_simple (a : List (B W)) (k : B W) :
    ¬ cs.IsReduced (a ++ [k, k]) := by
  intro hred
  have h1 : cs.wordProd (a ++ [k, k]) = cs.wordProd a := by
    simp only [wordProd_append, wordProd_cons, wordProd_nil, mul_one]
    rw [← mul_assoc, cs.simple_mul_simple_cancel_right]
  have h2 : cs.length (cs.wordProd a) ≤ a.length := cs.length_wordProd_le a
  unfold CoxeterSystem.IsReduced at hred
  rw [h1] at hred
  simp only [List.length_append, List.length_cons, List.length_nil] at hred
  omega

/-- A reduced word confined to two letters `i`, `i'` must be an alternating word, in one order or
the other: since a reduced word never repeats a letter in two consecutive positions
(`not_isReduced_append_simple_simple`), and a sequence over a two-letter alphabet with no
immediate repeats is determined entirely by its first letter and length. -/
theorem eq_alternatingWord_of_isReduced_of_confined {i i' : B W} {μ : List (B W)}
    (hred : cs.IsReduced μ) (hconf : ∀ k ∈ μ, k = i ∨ k = i') :
    μ = alternatingWord i i' μ.length ∨ μ = alternatingWord i' i μ.length := by
  induction μ using List.reverseRecOn with
  | nil => exact Or.inl rfl
  | append_singleton rest k ih =>
      have hred_rest : cs.IsReduced rest := isReduced_of_append_left hred
      have hconf_rest : ∀ m ∈ rest, m = i ∨ m = i' := fun m hm => hconf m (by simp [hm])
      have hk : i = k ∨ i' = k := (hconf k (by simp)).imp Eq.symm Eq.symm
      rcases Nat.eq_zero_or_pos rest.length with hL0 | hLpos
      · have hnil : rest = [] := List.length_eq_zero_iff.mp hL0
        subst hnil
        rcases hk with rfl | rfl
        · exact Or.inr rfl
        · exact Or.inl rfl
      · obtain ⟨L, hL⟩ : ∃ L, rest.length = L + 1 := ⟨rest.length - 1, by omega⟩
        rcases ih hred_rest hconf_rest with hrest | hrest
        · rw [hL] at hrest
          rcases hk with rfl | rfl
          · right
            have heq : rest ++ [i] = alternatingWord i' i (L + 2) := by
              rw [alternatingWord_succ i' i (L + 1), List.concat_eq_append, hrest]
            rw [heq]
            congr 1
            simp
          · exfalso
            rw [alternatingWord_succ i i' L, List.concat_eq_append] at hrest
            refine not_isReduced_append_simple_simple (alternatingWord i' i L) i' ?_
            rw [hrest, List.append_assoc] at hred
            exact hred
        · rw [hL] at hrest
          rcases hk with rfl | rfl
          · exfalso
            rw [alternatingWord_succ i' i L, List.concat_eq_append] at hrest
            refine not_isReduced_append_simple_simple (alternatingWord i i' L) i ?_
            rw [hrest, List.append_assoc] at hred
            exact hred
          · left
            have heq : rest ++ [i'] = alternatingWord i i' (L + 2) := by
              rw [alternatingWord_succ i i' (L + 1), List.concat_eq_append, hrest]
            rw [heq]
            congr 1
            simp

end Coxeter
