module

public import Coxeter.Basic
public import Mathlib.Algebra.MonoidAlgebra.Basic
public import Mathlib.Algebra.Polynomial.Laurent
public import Mathlib.Algebra.FreeAlgebra
public import Mathlib.Algebra.RingQuot
public import Mathlib.RingTheory.TensorProduct.Basic
public import Mathlib.RingTheory.TensorProduct.Maps
public import Coxeter.LinearAlgebra.AssociatedGraded
public import Coxeter.StrongExchange

/-!
# The Iwahori–Hecke algebra

The Iwahori–Hecke algebra of a Coxeter group,
which is the deformation of the group algebra of `W`.

This is the **multiparameter** (unequal parameter) Hecke algebra.
we work over the Laurent polynomial ring
`ℤ[v_i^{±1} : i ∈ B W]`
with one indeterminate `v_i` per simple reflection, and
Hecke parameter `q_i := v_i ^ 2` at `i`.
The `v_i` are forced equal (`heckeV_eq_of_odd`) whenever
`i`, `i'` are connected by a chain of *odd* Coxeter-matrix entries.

`HeckeAlgebra` is defined as the free `HeckeRing`-algebra
on the simple reflections `B W`, modulo the relations

* `T_i ^ 2 = (q_i - 1) • T_i + q_i • 1` for each simple reflection `T_i` (`T_simple_sq`), and
* `T_i T_{i'} T_i ⋯ = T_{i'} T_i T_{i'} ⋯` (`M i i'` factors on each side) for each pair of
  simple reflections `T_i`, `T_{i'}` (`T_simple_braid`).

The **bar involution** is the ring automorphism of `HeckeAlgebra`
sending `T_w ↦ (T_{w⁻¹})⁻¹`,
and is semilinear over the scalar automorphism
`Coxeter.barScalar : HeckeRing W ≃+* HeckeRing W`
sending `v_i ↦ v_i⁻¹` for each `i`.

## Main definitions

* `Coxeter.ParamIndex`, `Coxeter.HeckeRing`, `Coxeter.heckeV`, `Coxeter.heckeQ`
* `Coxeter.HeckeRingOne`, `Coxeter.heckeRingOneHom`
* `Coxeter.HeckeRel`, `Coxeter.HeckeAlgebra`
* `Coxeter.T_simple`, `Coxeter.T`
* `Coxeter.bar`

## Main statements

* `Coxeter.heckeV_eq_of_odd`
* `Coxeter.heckeRingOneHom_heckeV`
* `Coxeter.T_simple_sq`, `Coxeter.T_simple_braid`
* `Coxeter.T_one`
* `Coxeter.bar_T_involutive`

## TODO

`HeckeAlgebra` is presented by generators and relations,
but is not manifestly *free* of
rank `|W|` (i.e. that `{T_w : w ∈ W}` is a basis).

## References

* [humphreys1990] J. Humphreys, *Reflection Groups and Coxeter Groups*
* [bjorner2005] A. Björner and F. Brenti, *Combinatorics of Coxeter Groups*
-/

@[expose] public section

namespace Coxeter

open CoxeterGroup CoxeterSystem

noncomputable section BaseRings

/-- The equivalence relation on simple reflections
generated by "`M i i'` is odd": the standard
compatibility condition for multiparameter Hecke algebras,
since `s_i`, `s_{i'}` are conjugate in `W`
whenever they are connected by a chain of
odd Coxeter-matrix entries. -/
def paramSetoid (W : Type*) [CoxeterGroup W] : Setoid (B W) :=
  Relation.EqvGen.setoid (fun i i' => Odd (M i i'))

/-- The index set for Hecke parameters
simple reflections modulo `paramSetoid`
i.e. modulo the compatibility condition forcing `v_i = v_{i'}`
when `i`, `i'` are connected by a chain of odd Coxeter-matrix entries. -/
def ParamIndex (W : Type*) [CoxeterGroup W] : Type _ := Quotient (paramSetoid W)

/-- The multiparameter Laurent polynomial ring
`ℤ[v_i^{±1} : i ∈ ParamIndex W]`, with one
indeterminate per parameter class.
The Iwahori–Hecke algebra of a Coxeter system is defined over this ring. -/
abbrev HeckeRing (W : Type*) [CoxeterGroup W] : Type _ := AddMonoidAlgebra ℤ (ParamIndex W →₀ ℤ)

/-- `HeckeRing W` carries the ring involution `v_i ↦ v_i⁻¹` (negating exponents in the
multiparameter Laurent monomial) as its `star` operation. -/
instance {W : Type*} [CoxeterGroup W] : StarRing (HeckeRing W) where
  star := AddMonoidAlgebra.domCongr ℤ ℤ (AddEquiv.neg (ParamIndex W →₀ ℤ))
  star_involutive x := by
    ext m
    simp [AddMonoidAlgebra.domCongr_apply]
  star_mul x y := by
    change AddMonoidAlgebra.domCongr ℤ ℤ (AddEquiv.neg (ParamIndex W →₀ ℤ)) (x * y)
      = AddMonoidAlgebra.domCongr ℤ ℤ (AddEquiv.neg (ParamIndex W →₀ ℤ)) y
        * AddMonoidAlgebra.domCongr ℤ ℤ (AddEquiv.neg (ParamIndex W →₀ ℤ)) x
    rw [map_mul, mul_comm]
  star_add x y := map_add (AddMonoidAlgebra.domCongr ℤ ℤ (AddEquiv.neg (ParamIndex W →₀ ℤ))) x y

/-- The distinguished indeterminate `v_i`
at the simple reflection `i`. -/
def heckeV {W : Type*} [CoxeterGroup W] (i : B W) : HeckeRing W :=
  Finsupp.single (Finsupp.single (Quotient.mk (paramSetoid W) i) 1) 1

/-- The Hecke algebra parameter `q_i := v_i ^ 2`
at the simple reflection `i`. -/
def heckeQ {W : Type*} [CoxeterGroup W] (i : B W) : HeckeRing W := heckeV i * heckeV i

/-- The defining compatibility condition: `v_i` and `v_{i'}`
coincide whenever `M i i'` is odd
(in particular, whenever `s_i` and `s_{i'}` are conjugate
via a single odd braid relation). -/
theorem heckeV_eq_of_odd {W : Type*} [CoxeterGroup W] {i i' : B W} (h : Odd (M i i')) :
    heckeV i = heckeV i' := by
  unfold heckeV
  rw [Quotient.sound (Relation.EqvGen.rel i i' h)]

def paramAugment (W : Type*) [CoxeterGroup W] : (ParamIndex W →₀ ℤ) →+ ℤ :=
  (Finsupp.linearCombination ℤ (fun _ : ParamIndex W => (1 : ℤ))).toAddMonoidHom

/-- The classical single-parameter Hecke ring `ℤ[v, v⁻¹]` -/
abbrev HeckeRingOne := LaurentPolynomial ℤ

/-- `HeckeRingOne = ℤ[v, v⁻¹]` carries the ring involution `v ↦ v⁻¹` as its `star` operation. -/
instance : StarRing HeckeRingOne where
  star := LaurentPolynomial.invert
  star_involutive := LaurentPolynomial.involutive_invert
  star_mul x y := by
    change LaurentPolynomial.invert (x * y)
      = LaurentPolynomial.invert y * LaurentPolynomial.invert x
    rw [map_mul, mul_comm]
  star_add x y := map_add LaurentPolynomial.invert x y

/-- The **equal-parameter specialization**
The `ℤ`-algebra homomorphism sending every `v_i` to
the same `v` (`heckeRingOneHom_heckeV`)
collapsing the multiparameter Hecke ring `HeckeRing W`
to the classical single-parameter one `HeckeRingOne`.
Tensoring with `HeckeRingOne` over `HeckeRing W` gives the
classical single-parameter Iwahori–Hecke algebra.
It is compatible with `star` on both sides (`v_i ↦ v_i⁻¹` and `v ↦ v⁻¹`), i.e. a star algebra
homomorphism. -/
def heckeRingOneHom {W : Type*} [CoxeterGroup W] : HeckeRing W →⋆ₐ[ℤ] HeckeRingOne :=
  { AddMonoidAlgebra.mapDomainAlgHom ℤ ℤ (paramAugment W) with
    map_star' := fun x => by
      have h : (AddMonoidAlgebra.mapDomainAlgHom ℤ ℤ (paramAugment W)).comp
          (AddMonoidAlgebra.domCongr ℤ ℤ (AddEquiv.neg (ParamIndex W →₀ ℤ))
            : HeckeRing W →ₐ[ℤ] HeckeRing W)
        = (LaurentPolynomial.invert (R := ℤ)).toAlgHom.comp
          (AddMonoidAlgebra.mapDomainAlgHom ℤ ℤ (paramAugment W)) := by
        apply AddMonoidAlgebra.algHom_ext
        intro g
        simp [AddMonoidAlgebra.domCongr_single, map_neg]
      exact congrFun (congrArg DFunLike.coe h) x }

theorem heckeRingOneHom_heckeV {W : Type*} [CoxeterGroup W] (i : B W) :
    heckeRingOneHom (heckeV i) = LaurentPolynomial.T 1 := by
  unfold heckeV heckeRingOneHom
  rw [StarAlgHom.coe_mk', AddMonoidAlgebra.mapDomainAlgHom_apply, AddMonoidAlgebra.mapDomain_single]
  change Finsupp.single (paramAugment W (Finsupp.single (Quotient.mk (paramSetoid W) i) 1)) 1
    = Finsupp.single (1 : ℤ) 1
  congr 1
  simp [paramAugment, Finsupp.linearCombination_single]

/-- `paramAugment W` hits every integer already at a single simple reflection's class, so it is
surjective as soon as there is at least one simple reflection. -/
theorem paramAugment_surjective {W : Type*} [CoxeterGroup W] [Nonempty (B W)] :
    Function.Surjective (paramAugment W) := by
  obtain ⟨i⟩ := ‹Nonempty (B W)›
  intro n
  exact ⟨Finsupp.single (Quotient.mk (paramSetoid W) i) n, by
    simp [paramAugment, Finsupp.linearCombination_single]⟩

/-- The equal-parameter specialization `heckeRingOneHom` is surjective: every `v_i ↦ v`, so the
image already contains `v` and hence (being a ring homomorphism) every `v^n`, spanning all of
`HeckeRingOne = ℤ[v, v⁻¹]`. Needs at least one simple reflection (`Nonempty (B W)`) — with none,
`v` itself is never hit. -/
theorem heckeRingOneHom_surjective {W : Type*} [CoxeterGroup W] [Nonempty (B W)] :
    Function.Surjective (heckeRingOneHom (W := W)) := by
  intro s
  obtain ⟨x, hx⟩ := Finsupp.mapDomain_surjective (M := ℤ) (paramAugment_surjective (W := W)) s
  refine ⟨x, ?_⟩
  unfold heckeRingOneHom
  rw [StarAlgHom.coe_mk', AddMonoidAlgebra.mapDomainAlgHom_apply]
  exact hx

end BaseRings

section MultiparamDef

/-- The defining relations of the Iwahori–Hecke algebra
imposed on the free algebra on the simple reflections
- The quadratic relation for each generator
- The braid relation for each pair of generators.
-/
inductive HeckeRel (W : Type*) [CoxeterGroup W] :
    FreeAlgebra (HeckeRing W) (B W) → FreeAlgebra (HeckeRing W) (B W) → Prop
  | quad (i : B W) :
      HeckeRel W (FreeAlgebra.ι (HeckeRing W) i * FreeAlgebra.ι (HeckeRing W) i)
        ((heckeQ i - 1) • FreeAlgebra.ι (HeckeRing W) i + heckeQ i • 1)
  | braid (i i' : B W) :
      HeckeRel W ((braidWord M i i').map (FreeAlgebra.ι (HeckeRing W))).prod
        ((braidWord M i' i).map (FreeAlgebra.ι (HeckeRing W))).prod

/-- The **Iwahori–Hecke algebra**
The free `HeckeRing`-algebra on the simple reflections,
modulo the quadratic and braid relations (`HeckeRel`).
Its `Ring`/`Algebra` structure comes for free from `RingQuot`. -/
abbrev HeckeAlgebra (W : Type*) [CoxeterGroup W] : Type _ := RingQuot (HeckeRel W)

variable {W : Type*} [CoxeterGroup W] [mat : Matsumoto (W1 := W)]

/-- The generator `T_i` of the Hecke algebra. -/
noncomputable def T_simple (i : B W) : HeckeAlgebra W :=
  RingQuot.mkAlgHom (HeckeRing W) (HeckeRel W) (FreeAlgebra.ι (HeckeRing W) i)

omit mat in
theorem T_simple_sq (i : B W) :
    T_simple i * T_simple i = (heckeQ i - 1) • T_simple i + heckeQ i • (1 : HeckeAlgebra W) := by
  have h := RingQuot.mkAlgHom_rel (HeckeRing W) (HeckeRel.quad (W := W) i)
  simpa [T_simple, map_mul, map_add, map_smul, map_one] using h

omit mat in
theorem T_simple_braid (i i' : B W) :
    ((braidWord M i i').map T_simple).prod = ((braidWord M i' i).map T_simple).prod := by
  have h := RingQuot.mkAlgHom_rel (HeckeRing W) (HeckeRel.braid (W := W) i i')
  simpa [T_simple, map_list_prod] using h

/-- The standard basis element `T_w`
The product of the generators `T_simple` along an
(arbitrarily chosen) reduced word for `w`.
Independence from that choice is deferred -/
noncomputable def T (w : W) : HeckeAlgebra W :=
  ((Classical.arbitrary (ReducedWord w)).val.map T_simple).prod

omit mat in
theorem T_one : T (1 : W) = 1 := by
  simp only [T]
  set ω := Classical.arbitrary (ReducedWord (1 : W)) with hω
  have hlen : ω.val.length = 0 := by rw [ω.length_eq, cs.length_one]
  have hnil : ω.val = [] := List.eq_nil_of_length_eq_zero hlen
  simp [hnil]

omit mat in
/-- A single elementary braid move (`Coxeter.BraidMove`) between two words doesn't change the
`T_simple`-product, since it's exactly the braid relation `T_simple_braid`. -/
theorem BraidMove.T_simple_prod_eq {ω ω' : List (B W)} (h : BraidMove ω ω') :
    (ω.map T_simple).prod = (ω'.map T_simple).prod := by
  obtain ⟨i, i', α, β, hω, hω'⟩ := h
  rw [hω, hω']
  simp only [List.map_append, List.prod_append, T_simple_braid]

/-- `T w` doesn't depend on the choice of reduced word: it equals the `T_simple`-product along
*any* reduced word for `w`, not just the one used in the definition. This is where Matsumoto's
theorem (`Coxeter.eqvGen_braidMove_of_reduced`) is actually used: any two reduced words for `w`
are connected by a chain of braid moves, each of which preserves the `T_simple`-product
(`BraidMove.T_simple_prod_eq`). -/
theorem T_eq_of_reducedWord {w : W} (ω : ReducedWord w) :
    T w = (ω.val.map T_simple).prod := by
  simp only [T]
  set ω₀ := Classical.arbitrary (ReducedWord w) with hω₀
  clear_value ω₀
  clear hω₀
  have h : Relation.EqvGen BraidMove ω₀.val ω.val := mat.reduced_words_convert w ω₀ ω
  generalize ω₀.val = l₀ at h ⊢
  generalize ω.val = l at h ⊢
  clear ω₀ ω
  induction h with
  | rel a b hab => exact hab.T_simple_prod_eq
  | refl a => rfl
  | symm a b _ ih => exact ih.symm
  | trans a b c _ _ ih1 ih2 => exact ih1.trans ih2

theorem T_mul_T_of_length_add {u w : W}
  (h : cs.length (u * w) =
  cs.length u + cs.length w) :
  T u * T w = T (u * w) := by
  set ω := Classical.arbitrary (ReducedWord (w : W)) with hω
  set υ := Classical.arbitrary (ReducedWord (u : W)) with hυ
  have hred : cs.IsReduced (υ.val ++ ω.val) := by
    unfold CoxeterSystem.IsReduced
    rw [wordProd_append, υ.wordProd_eq, ω.wordProd_eq, h, List.length_append, υ.length_eq,
      ω.length_eq]
  have hwordProd : u * w = cs.wordProd (υ.val ++ ω.val) := by
    rw [wordProd_append, υ.wordProd_eq, ω.wordProd_eq]
  set ωυ : ReducedWord (u * w) := ⟨υ.val ++ ω.val, hred, hwordProd⟩
  calc T u * T w = (υ.val.map T_simple).prod * (ω.val.map T_simple).prod := by
        rw [T_eq_of_reducedWord υ, T_eq_of_reducedWord ω]
    _ = ((υ.val ++ ω.val).map T_simple).prod := by
        rw [List.map_append, List.prod_append]
    _ = T (u * w) := (T_eq_of_reducedWord ωυ).symm

@[simp]
theorem T_simple_eq_T (i : B W) : T (cs.simple i) = T_simple i := by
  let ω : ReducedWord (cs.simple i) := ⟨[i], isReduced_singleton i, by rw [wordProd_singleton]⟩
  rw [T_eq_of_reducedWord ω]
  rw [List.map_cons, List.map_nil, List.prod_cons, List.prod_nil, mul_one]

theorem T_mul_T_simple_of_not_rightDescent {w : W} {i : B W}
    (h : ¬ cs.IsRightDescent w i) :
    T w * T_simple i = T (w * cs.simple i) := by
  rw [← T_simple_eq_T i]
  exact T_mul_T_of_length_add (by rw [cs.not_isRightDescent_iff.mp h, cs.length_simple])

theorem T_mul_T_simple_of_rightDescent {w : W} {i : B W}
    (h : cs.IsRightDescent w i) :
    T w * T_simple i =
      (heckeQ i - 1) • T w + heckeQ i • T (w * cs.simple i) := by
  have hnot : ¬ cs.IsRightDescent (w * cs.simple i) i :=
    (cs.isRightDescent_iff_not_isRightDescent_mul.mp h)
  have hmul := T_mul_T_simple_of_not_rightDescent (w := w * cs.simple i) (i := i) hnot
  have hcancel : (w * cs.simple i) * cs.simple i = w := cs.simple_mul_simple_cancel_right i
  calc
    T w * T_simple i = (T (w * cs.simple i) * T_simple i) * T_simple i := by
      rw [hmul, hcancel]
    _ = T (w * cs.simple i) * (T_simple i * T_simple i) := by
      rw [mul_assoc]
    _ = T (w * cs.simple i) *
        ((heckeQ i - 1) • T_simple i + heckeQ i • (1 : HeckeAlgebra W)) := by
      rw [T_simple_sq]
    _ = (heckeQ i - 1) • T w + heckeQ i • T (w * cs.simple i) := by
      rw [mul_add, mul_smul_comm, mul_smul_comm, mul_one, hmul, hcancel]

theorem T_mul_T_simple_mem_span {i : B W} {x : HeckeAlgebra W}
    (hx : x ∈ Submodule.span (HeckeRing W) (Set.range (T (W := W)))) :
    x * T_simple i ∈ Submodule.span (HeckeRing W) (Set.range (T (W := W))) := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
      obtain ⟨w, rfl⟩ := hx
      by_cases h : cs.IsRightDescent w i
      · rw [T_mul_T_simple_of_rightDescent h]
        exact Submodule.add_mem _ (Submodule.smul_mem _ _ (Submodule.subset_span ⟨w, rfl⟩))
          (Submodule.smul_mem _ _ (Submodule.subset_span ⟨w * cs.simple i, rfl⟩))
      · rw [T_mul_T_simple_of_not_rightDescent h]
        exact Submodule.subset_span ⟨w * cs.simple i, rfl⟩
  | zero =>
      rw [zero_mul]
      exact Submodule.zero_mem _
  | add x y _ _ hx hy =>
      rw [add_mul]
      exact Submodule.add_mem _ hx hy
  | smul c x _ hx =>
      rw [smul_mul_assoc]
      exact Submodule.smul_mem _ c hx

end MultiparamDef

section LengthFiltration

variable {W : Type*} [CoxeterGroup W] [mat : Matsumoto (W1 := W)]

/-- Monomials of length at most `n` in the simple Hecke generators. -/
noncomputable def heckeLengthFiltrationMonomials (n : ℕ) : Set (HeckeAlgebra W) :=
  {x | ∃ l : List (B W), l.length ≤ n ∧ (l.map T_simple).prod = x}

/-- The length filtration on `HeckeAlgebra W`.
`F_n` is the `HeckeRing W`-span of products of
at most `n` simple generators. -/
noncomputable def heckeLengthFiltration (n : ℕ) : Submodule (HeckeRing W) (HeckeAlgebra W) :=
  Submodule.span (HeckeRing W) (heckeLengthFiltrationMonomials (W := W) n)

omit mat in
theorem one_mem_heckeLengthFiltration (n : ℕ) :
    (1 : HeckeAlgebra W) ∈ heckeLengthFiltration (W := W) n := by
  refine Submodule.subset_span ?_
  exact ⟨[], by simp, by simp⟩

omit mat in
theorem algebraMap_mem_heckeLengthFiltration_zero (c : HeckeRing W) :
    algebraMap (HeckeRing W) (HeckeAlgebra W) c ∈ heckeLengthFiltration (W := W) 0 := by
  simpa [Algebra.smul_def] using
    Submodule.smul_mem (heckeLengthFiltration (W := W) 0) c
      (one_mem_heckeLengthFiltration (W := W) 0)

omit mat in
theorem T_simple_mem_heckeLengthFiltration_one (i : B W) :
    T_simple i ∈ heckeLengthFiltration (W := W) 1 := by
  refine Submodule.subset_span ?_
  exact ⟨[i], by simp, by simp⟩

omit mat in
theorem T_prod_mem_heckeLengthFiltration {l : List (B W)} {n : ℕ} (h : l.length ≤ n) :
    (l.map T_simple).prod ∈ heckeLengthFiltration (W := W) n := by
  exact Submodule.subset_span ⟨l, h, rfl⟩

theorem T_mem_heckeLengthFiltration (w : W) :
    T w ∈ heckeLengthFiltration (W := W) (cs.length w) := by
  let ω : ReducedWord w := Classical.arbitrary (ReducedWord w)
  rw [T_eq_of_reducedWord ω]
  exact T_prod_mem_heckeLengthFiltration (W := W) (by rw [ω.length_eq])

omit mat in
theorem heckeLengthFiltrationMonomials_mono {m n : ℕ} (h : m ≤ n) :
    heckeLengthFiltrationMonomials (W := W) m ⊆ heckeLengthFiltrationMonomials (W := W) n := by
  rintro x ⟨l, hl, rfl⟩
  exact ⟨l, hl.trans h, rfl⟩

omit mat in
/-- The length filtration is monotone:
a monomial of length at most `m` is also of length at most `n`
for `m ≤ n`. -/
theorem heckeLengthFiltration_mono : Monotone (heckeLengthFiltration (W := W)) := by
  intro m n h
  exact Submodule.span_mono (heckeLengthFiltrationMonomials_mono h)

omit mat in
/-- The length filtration is submultiplicative:
`heckeLengthFiltration m * heckeLengthFiltration n ⊆ heckeLengthFiltration (m + n)`,
since concatenating a monomial of length `≤ m` with one of length `≤ n`
gives a monomial of length `≤ m + n`. -/
theorem heckeLengthFiltration_mul_mem {m n : ℕ} {x y : HeckeAlgebra W}
    (hx : x ∈ heckeLengthFiltration (W := W) m) (hy : y ∈ heckeLengthFiltration (W := W) n) :
    x * y ∈ heckeLengthFiltration (W := W) (m + n) := by
  induction hx, hy using Submodule.span_induction₂ with
  | mem_mem x y hx hy =>
      obtain ⟨l1, hl1, rfl⟩ := hx
      obtain ⟨l2, hl2, rfl⟩ := hy
      rw [← List.prod_append, ← List.map_append]
      exact T_prod_mem_heckeLengthFiltration (by rw [List.length_append]; omega)
  | zero_left y hy => simp
  | zero_right x hx => simp
  | add_left x y z hx hy hz ihx ihy => rw [add_mul]; exact Submodule.add_mem _ ihx ihy
  | add_right x y z hx hy hz ihy ihz => rw [mul_add]; exact Submodule.add_mem _ ihy ihz
  | smul_left r x y hx hy ih => rw [smul_mul_assoc]; exact Submodule.smul_mem _ r ih
  | smul_right r x y hx hy ih => rw [mul_smul_comm]; exact Submodule.smul_mem _ r ih

/-- The length filtration on `HeckeAlgebra W`, bundled as a `Coxeter.Filtration`:
this unlocks the general associated graded machinery
(`Coxeter.Filtration.AssociatedGraded`, its `Ring`/`Algebra (HeckeRing W)` structure)
for free. -/
noncomputable def heckeLengthCoxeterFiltration : Filtration (HeckeRing W) (HeckeAlgebra W) where
  carrier := heckeLengthFiltration
  mono := heckeLengthFiltration_mono
  one_mem := one_mem_heckeLengthFiltration 0
  mul_mem hx hy := heckeLengthFiltration_mul_mem hx hy

end LengthFiltration

section OneParameterSpecialization

variable {W : Type*} [CoxeterGroup W]

open TensorProduct

/-- `HeckeRingOne` as a `HeckeRing W`-algebra, by restricting scalars along the ring homomorphism
`heckeRingOneHom : HeckeRing W →+* HeckeRingOne`. -/
noncomputable instance : Algebra (HeckeRing W) HeckeRingOne :=
  (heckeRingOneHom.toAlgHom.toRingHom : HeckeRing W →+* HeckeRingOne).toAlgebra

/-- The classical single-parameter Iwahori–Hecke algebra: the base change of the multiparameter
`HeckeAlgebra W` along `heckeRingOneHom : HeckeRing W → HeckeRingOne`. As a `HeckeRingOne`-algebra
(not just a `HeckeRing W`-module), via `Algebra.TensorProduct.rightAlgebra`. -/
abbrev HeckeAlgebraOne (W : Type*) [CoxeterGroup W] : Type _ :=
  HeckeAlgebra W ⊗[HeckeRing W] HeckeRingOne

noncomputable instance : Algebra HeckeRingOne (HeckeAlgebraOne W) :=
  Algebra.TensorProduct.rightAlgebra


/-- The base-change map `HeckeAlgebra W → HeckeAlgebraOne W`, `a ↦ a ⊗ₜ 1`, is surjective: since
`heckeRingOneHom_surjective` says `HeckeRing W → HeckeRingOne` is already surjective, every pure
tensor `a ⊗ₜ s` is hit (writing `s = heckeRingOneHom r` gives `a ⊗ₜ s = (r • a) ⊗ₜ 1`), and a
general element of the tensor product is a finite sum of pure tensors. -/
theorem heckeAlgebraOne_includeLeft_surjective [Nonempty (B W)] :
    Function.Surjective (Algebra.TensorProduct.includeLeft :
      HeckeAlgebra W →ₐ[HeckeRing W] HeckeAlgebraOne W) :=
  Algebra.TensorProduct.includeLeft_surjective _ _ heckeRingOneHom_surjective

section QOneSpecialization

/-- The **`q = 1` specialization**: evaluating the classical single-parameter Hecke ring
`HeckeRingOne = ℤ[v, v⁻¹]` at `v = 1` (so `q_i = v_i^2 = 1` too, once composed with
`heckeRingOneHom`). -/
noncomputable def qOneHom : HeckeRingOne →+* ℤ :=
  LaurentPolynomial.eval₂ (RingHom.id ℤ) (1 : ℤˣ)

theorem qOneHom_surjective : Function.Surjective qOneHom :=
  fun n => ⟨LaurentPolynomial.C n, LaurentPolynomial.eval₂_C ..⟩

theorem qOneHom_T (n : ℤ) : qOneHom (LaurentPolynomial.T n) = 1 := by
  simp [qOneHom, LaurentPolynomial.eval₂_T]

/-- The composite `HeckeRing W → HeckeRingOne → ℤ → ℤ[W]`, `v_i ↦ 1` for every `i`: the ring
homomorphism making `MonoidAlgebra ℤ W` a `HeckeRing W`-algebra for the `q = 1` specialization. -/
noncomputable def qOneRingHom : HeckeRing W →+* MonoidAlgebra ℤ W :=
  (algebraMap ℤ (MonoidAlgebra ℤ W)).comp (qOneHom.comp heckeRingOneHom.toAlgHom.toRingHom)

theorem qOneRingHom_heckeQ (i : B W) : qOneRingHom (heckeQ i) = 1 := by
  simp [qOneRingHom, heckeQ, map_mul, heckeRingOneHom_heckeV, qOneHom_T,
    MonoidAlgebra.one_def]

/-- The scalar augmentation on the multiparameter Hecke ring, evaluating every `v_i` at `1`. -/
noncomputable def qOneScalarHom : HeckeRing W →+* ℤ :=
  qOneHom.comp heckeRingOneHom.toAlgHom.toRingHom

@[simp]
theorem qOneScalarHom_heckeQ (i : B W) : qOneScalarHom (heckeQ i) = 1 := by
  simp [qOneScalarHom, heckeQ, map_mul, heckeRingOneHom_heckeV, qOneHom_T]

/-- The image of `qOneRingHom` is central (it factors through `ℤ`), so it defines a genuine
`HeckeRing W`-algebra structure on `MonoidAlgebra ℤ W`, even though the latter is generally
noncommutative. -/
noncomputable instance : Algebra (HeckeRing W) (MonoidAlgebra ℤ W) :=
  qOneRingHom.toAlgebra' fun c x => Algebra.commutes (qOneHom (heckeRingOneHom c)) x

@[simp]
theorem algebraMap_qOneScalarHom (c : HeckeRing W) :
    algebraMap (HeckeRing W) (MonoidAlgebra ℤ W) c =
      (qOneScalarHom c : MonoidAlgebra ℤ W) := rfl

theorem algebraMap_heckeQ (i : B W) :
    algebraMap (HeckeRing W) (MonoidAlgebra ℤ W) (heckeQ i) = 1 :=
  qOneRingHom_heckeQ i

/-- The `HeckeRing W`-algebra homomorphism from the free algebra on the simple reflections to
`ℤ[W]`, sending each generator `T_i` to the group element `s_i`. -/
noncomputable def qOneFreeAlgHom :
    FreeAlgebra (HeckeRing W) (B W) →ₐ[HeckeRing W] MonoidAlgebra ℤ W :=
  FreeAlgebra.lift (HeckeRing W) (fun i => MonoidAlgebra.single (cs.simple i) (1 : ℤ))

@[simp] theorem qOneFreeAlgHom_ι (i : B W) :
    qOneFreeAlgHom (FreeAlgebra.ι (HeckeRing W) i) = MonoidAlgebra.single (cs.simple i) (1 : ℤ) :=
  FreeAlgebra.lift_ι_apply _ _

theorem qOneFreeAlgHom_wordProd (l : List (B W)) :
    qOneFreeAlgHom ((l.map (FreeAlgebra.ι (HeckeRing W))).prod)
      = MonoidAlgebra.single (cs.wordProd l) (1 : ℤ) := by
  induction l with
  | nil => simp [MonoidAlgebra.one_def]
  | cons j l ih =>
      rw [List.map_cons, List.prod_cons, map_mul, qOneFreeAlgHom_ι, ih,
        MonoidAlgebra.single_mul_single, one_mul, wordProd_cons]

theorem qOneFreeAlgHom_respects_rel : ∀ ⦃x y⦄, HeckeRel W x y →
    qOneFreeAlgHom x = qOneFreeAlgHom y := by
  intro x y h
  cases h with
  | quad i =>
      rw [map_mul, qOneFreeAlgHom_ι, MonoidAlgebra.single_mul_single, mul_one,
        cs.simple_mul_simple_self, ← MonoidAlgebra.one_def, map_add, map_smul, map_smul,
        qOneFreeAlgHom_ι, map_one]
      simp [Algebra.smul_def, MonoidAlgebra.one_def]
  | braid i i' =>
      rw [qOneFreeAlgHom_wordProd, qOneFreeAlgHom_wordProd, wordProd_braidWord_eq]

/-- The `HeckeRing W`-algebra homomorphism `HeckeAlgebra W → ℤ[W]` induced by `qOneFreeAlgHom`
via the universal property of `RingQuot`, sending `T_i ↦ s_i`. -/
noncomputable def qOneAlgHom0 : HeckeAlgebra W →ₐ[HeckeRing W] MonoidAlgebra ℤ W :=
  RingQuot.liftAlgHom (HeckeRing W) ⟨qOneFreeAlgHom, qOneFreeAlgHom_respects_rel⟩

theorem qOneFreeAlgHom_surjective : Function.Surjective (qOneFreeAlgHom (W := W)) := by
  intro s
  induction s using Finsupp.induction with
  | zero => exact ⟨0, map_zero _⟩
  | single_add w n f _hw _hn ih =>
      obtain ⟨x, hx⟩ := ih
      obtain ⟨l, hl⟩ := cs.wordProd_surjective w
      refine ⟨n • ((l.map (FreeAlgebra.ι (HeckeRing W))).prod) + x, ?_⟩
      rw [map_add, map_zsmul, qOneFreeAlgHom_wordProd, hl, hx]
      congr 1
      rw [zsmul_eq_mul (MonoidAlgebra.single w 1) n]
      change (n : MonoidAlgebra ℤ W) * MonoidAlgebra.single w 1 = MonoidAlgebra.single w n
      rw [show (n : MonoidAlgebra ℤ W) = MonoidAlgebra.single (1 : W) n by rfl]
      rw [MonoidAlgebra.single_mul_single]
      simp

theorem qOneAlgHom0_surjective : Function.Surjective (qOneAlgHom0 (W := W)) := by
  have heq : qOneAlgHom0.comp (RingQuot.mkAlgHom (HeckeRing W) (HeckeRel W))
      = qOneFreeAlgHom := by
    apply FreeAlgebra.hom_ext
    funext x
    exact RingQuot.liftAlgHom_mkAlgHom_apply (HeckeRing W) qOneFreeAlgHom
      qOneFreeAlgHom_respects_rel (FreeAlgebra.ι (HeckeRing W) x)
  exact Function.Surjective.of_comp (f := qOneAlgHom0)
    (g := RingQuot.mkAlgHom (HeckeRing W) (HeckeRel W)) (show Function.Surjective
      (qOneAlgHom0.comp (RingQuot.mkAlgHom (HeckeRing W) (HeckeRel W))) from by
        rw [heq]
        exact qOneFreeAlgHom_surjective)

/-- `HeckeRingOne` maps into `ℤ[W]` as a `HeckeRing W`-algebra homomorphism, via `qOneHom`. -/
noncomputable def qOneRingHomOne : HeckeRingOne →ₐ[HeckeRing W] MonoidAlgebra ℤ W where
  toRingHom := (algebraMap ℤ (MonoidAlgebra ℤ W)).comp qOneHom
  commutes' _ := rfl

theorem qOneAlgHom0_commute (x : HeckeAlgebra W) (y : HeckeRingOne) :
    Commute (qOneAlgHom0 x) (qOneRingHomOne y) :=
  (Algebra.commutes (qOneHom y) (qOneAlgHom0 x)).symm

/-- At `q = 1`, the quadratic relation `T_i ^ 2 = (q_i - 1) • T_i + q_i • 1` degenerates to
`T_i ^ 2 = 1`, exactly the defining relation `s_i ^ 2 = 1` of the group `W`; the braid relations
carry over unchanged (`qOneFreeAlgHom_respects_rel`). So the single-parameter Hecke algebra
`HeckeAlgebraOne W`, further specialized along `qOneHom` (`v ↦ 1`), collapses onto the integral
group algebra `MonoidAlgebra ℤ W`, via the ℤ-algebra homomorphism sending `T_w ⊗ₜ 1 ↦
Finsupp.single w 1`. -/
noncomputable def qOneAlgHom : HeckeAlgebraOne W →ₐ[ℤ] MonoidAlgebra ℤ W where
  toRingHom := (Algebra.TensorProduct.lift (S := HeckeRing W) qOneAlgHom0 qOneRingHomOne
    qOneAlgHom0_commute).toRingHom
  commutes' n := by simp

theorem qOneAlgHom_surjective : Function.Surjective (qOneAlgHom (W := W)) := by
  intro c
  obtain ⟨a, ha⟩ := qOneAlgHom0_surjective c
  exact ⟨a ⊗ₜ[HeckeRing W] 1, by
    change Algebra.TensorProduct.lift qOneAlgHom0 qOneRingHomOne qOneAlgHom0_commute
      (a ⊗ₜ[HeckeRing W] 1) = c
    rw [Algebra.TensorProduct.lift_tmul, map_one, mul_one, ha]⟩

/-- At `q = 1`, the simple Hecke generator maps to the corresponding group-algebra basis
element. -/
theorem qOneAlgHom0_T_simple (i : B W) :
    qOneAlgHom0 (T_simple i) = MonoidAlgebra.single (cs.simple i) (1 : ℤ) := by
  simp [qOneAlgHom0, T_simple,
    RingQuot.liftAlgHom_mkAlgHom_apply (HeckeRing W) qOneFreeAlgHom
      qOneFreeAlgHom_respects_rel (FreeAlgebra.ι (HeckeRing W) i)]

/-- At `q = 1`, the Hecke word product along any word maps to the corresponding group-algebra
basis element. -/
theorem qOneAlgHom0_T_prod (l : List (B W)) :
    qOneAlgHom0 ((l.map T_simple).prod) = MonoidAlgebra.single (cs.wordProd l) (1 : ℤ) := by
  induction l with
  | nil => simp [MonoidAlgebra.one_def]
  | cons i l ih =>
      rw [List.map_cons, List.prod_cons, map_mul, qOneAlgHom0_T_simple, ih,
        MonoidAlgebra.single_mul_single, one_mul, wordProd_cons]

/-- At `q = 1`, `T_w` specializes to the standard group-algebra basis vector indexed by `w`. -/
theorem qOneAlgHom0_T (w : W) [Matsumoto (W1 := W)] :
    qOneAlgHom0 (T w) = MonoidAlgebra.single w (1 : ℤ) := by
  let ω : ReducedWord w := Classical.arbitrary (ReducedWord w)
  rw [T_eq_of_reducedWord ω, qOneAlgHom0_T_prod, ω.wordProd_eq]

/-- The specialized elements `qOneAlgHom0 (T_w)` are linearly independent over `ℤ`, because
they are exactly the standard basis of the group algebra. -/
theorem qOneAlgHom0_T_linearIndependent [Matsumoto (W1 := W)] :
    LinearIndependent ℤ (fun w : W => qOneAlgHom0 (T w)) := by
  simpa [qOneAlgHom0_T, MonoidAlgebra.basis_apply] using
    (MonoidAlgebra.basis W ℤ).linearIndependent

end QOneSpecialization

end OneParameterSpecialization

section Dihedral

variable {W : Type*} [CoxeterGroup W]

/-- The rank-2 parabolic subgroup generated by two simple reflections. -/
def rankTwoSubgroup (i i' : B W) : Subgroup W := Subgroup.closure {cs.simple i, cs.simple i'}

/-- Every element of `rankTwoSubgroup i i'`
can be written as `cs.wordProd μ` for some
(not necessarily reduced) word `μ`
using only the letters `i`, `i'`. -/
private theorem exists_confined_word
  {i i' : B W} {v : W}
  (hv : v ∈ rankTwoSubgroup i i') :
  ∃ μ : List (B W),
    v = cs.wordProd μ ∧ ∀ k ∈ μ, k = i ∨ k = i' := by
  induction hv using Subgroup.closure_induction with
  | mem x hx =>
      rcases hx with h | h
      · exact ⟨[i], by rw [wordProd_singleton, h], by simp⟩
      · exact ⟨[i'], by rw [wordProd_singleton, h], by simp⟩
  | one => exact ⟨[], by rw [wordProd_nil], by simp⟩
  | mul x y _ _ ihx ihy =>
      obtain ⟨μx, hμx1, hμx2⟩ := ihx
      obtain ⟨μy, hμy1, hμy2⟩ := ihy
      refine ⟨μx ++ μy, ?_, ?_⟩
      · rw [wordProd_append, ← hμx1, ← hμy1]
      · intro k hk
        rcases List.mem_append.mp hk with hk | hk
        · exact hμx2 k hk
        · exact hμy2 k hk
  | inv x _ ihx =>
      obtain ⟨μ, hμ1, hμ2⟩ := ihx
      refine ⟨μ.reverse, ?_, ?_⟩
      · rw [hμ1, wordProd_reverse]
      · intro k hk
        exact hμ2 k (List.mem_reverse.mp hk)

/-- Every element of `rankTwoSubgroup i i'`
has a **reduced** word using only the letters
`i`, `i'`. -/
theorem exists_confined_reduced_word
  {i i' : B W} {v : W}
  (hv : v ∈ rankTwoSubgroup i i') :
  ∃ μ : List (B W),
    cs.IsReduced μ ∧ v = cs.wordProd μ ∧ ∀ k ∈ μ, k = i ∨ k = i' := by
  obtain ⟨μ₀, hμ₀1, hμ₀2⟩ := exists_confined_word hv
  obtain ⟨μ, hsub, hred, heq⟩ := exists_reduced_subword μ₀
  exact ⟨μ, hred, hμ₀1.trans heq, fun k hk => hμ₀2 k (hsub.subset hk)⟩

end Dihedral

section ActOnGroupAlgebra

variable {W : Type*} [CoxeterGroup W]

abbrev module_actedOn (W : Type*) [CoxeterGroup W] : Type _ := MonoidAlgebra (HeckeRing W) W

open Classical in
/-- The action of `T_i` on `module_actedOn W`, specified on the standard basis `single w 1` by
the same case-split formula as `T_mul_T_simple_of_rightDescent`/
`T_mul_T_simple_of_not_rightDescent` (right multiplication by `T_simple i` on the `HeckeAlgebra`
basis `T_w`), then extended `HeckeRing W`-linearly. -/
noncomputable def T_simple_action (i : B W) : Module.End (HeckeRing W) (module_actedOn W) :=
  Finsupp.lift (module_actedOn W) (HeckeRing W) W (fun w =>
    if cs.IsRightDescent w i then
      (heckeQ i - 1) • MonoidAlgebra.single w (1 : HeckeRing W)
        + heckeQ i • MonoidAlgebra.single (w * cs.simple i) (1 : HeckeRing W)
    else
      MonoidAlgebra.single (w * cs.simple i) (1 : HeckeRing W))

open Classical in
theorem T_simple_action_apply (i : B W) (w : W) :
    T_simple_action i (MonoidAlgebra.single w (1 : HeckeRing W)) =
      if cs.IsRightDescent w i then
        (heckeQ i - 1) • MonoidAlgebra.single w (1 : HeckeRing W)
          + heckeQ i • MonoidAlgebra.single (w * cs.simple i) (1 : HeckeRing W)
      else
        MonoidAlgebra.single (w * cs.simple i) (1 : HeckeRing W) := by
  change Finsupp.lift _ _ _ _ (Finsupp.single w (1 : HeckeRing W)) = _
  rw [Finsupp.lift_apply, Finsupp.sum_single_index (by simp), one_smul]

/-- The action `T_simple_action` satisfies the Hecke quadratic relation, by the same case-split
calculation as `T_mul_T_simple_of_rightDescent` (mirrored here directly on `module_actedOn W`,
since `{T_w}` isn't known to be a basis yet). -/
theorem T_simple_action_sq (i : B W) :
    T_simple_action i * T_simple_action i
      = (heckeQ i - 1) • T_simple_action i
        + heckeQ i • (1 : Module.End (HeckeRing W) (module_actedOn W)) := by
  apply MonoidAlgebra.lhom_ext'
  intro w
  apply LinearMap.ext_ring
  simp only [LinearMap.comp_apply, MonoidAlgebra.lsingle_apply, Module.End.mul_apply,
    LinearMap.add_apply, LinearMap.smul_apply, Module.End.one_apply]
  rw [T_simple_action_apply]
  by_cases h : cs.IsRightDescent w i
  · have hnot : ¬ cs.IsRightDescent (w * cs.simple i) i :=
      cs.isRightDescent_iff_not_isRightDescent_mul.mp h
    simp only [h, if_true]
    rw [map_add, map_smul, map_smul, T_simple_action_apply, T_simple_action_apply]
    simp only [h, hnot, if_true, if_false, cs.simple_mul_simple_cancel_right]
  · have hw : cs.IsRightDescent (w * cs.simple i) i := by
      by_contra hcon
      exact h (cs.isRightDescent_iff_not_isRightDescent_mul.mpr hcon)
    simp only [h, if_false]
    rw [T_simple_action_apply]
    simp only [hw, if_true, cs.simple_mul_simple_cancel_right]

/-- The action `T_simple_action` satisfies the Hecke braid relation: deferred, comparable in
difficulty to Matsumoto's theorem (see the module `TODO`). -/
theorem T_simple_action_braid (i i' : B W) :
    ((braidWord M i i').map T_simple_action).prod
      = ((braidWord M i' i).map T_simple_action).prod :=
  sorry

/-- The `HeckeRing W`-algebra homomorphism from the free algebra on the simple reflections to
`Module.End (HeckeRing W) (module_actedOn W)`, sending each generator `T_i` to its action
`T_simple_action i`. -/
noncomputable def heckeActionFreeAlgHom :
    FreeAlgebra (HeckeRing W) (B W) →ₐ[HeckeRing W] Module.End (HeckeRing W) (module_actedOn W) :=
  FreeAlgebra.lift (HeckeRing W) T_simple_action

theorem heckeActionFreeAlgHom_wordProd (l : List (B W)) :
    heckeActionFreeAlgHom ((l.map (FreeAlgebra.ι (HeckeRing W))).prod)
      = (l.map T_simple_action).prod := by
  induction l with
  | nil => simp [heckeActionFreeAlgHom]
  | cons j l ih =>
      rw [List.map_cons, List.prod_cons, map_mul, List.map_cons, List.prod_cons, ih]
      congr 1
      simp [heckeActionFreeAlgHom]

theorem heckeActionFreeAlgHom_respects_rel : ∀ ⦃x y⦄, HeckeRel W x y →
    heckeActionFreeAlgHom x = heckeActionFreeAlgHom y := by
  intro x y h
  cases h with
  | quad i =>
      simp only [heckeActionFreeAlgHom, map_mul, map_add, map_smul, map_one,
        FreeAlgebra.lift_ι_apply]
      exact T_simple_action_sq i
  | braid i i' =>
      rw [heckeActionFreeAlgHom_wordProd, heckeActionFreeAlgHom_wordProd]
      exact T_simple_action_braid i i'

/-- The algebra map from `HeckeAlgebra`, presented by generators and relations, to
`Module.End (HeckeRing W) (module_actedOn W)`: the action of the Hecke algebra on the free
`HeckeRing W`-module on `W`, specified (via the universal property of `RingQuot`) purely by
declaring the action of each generator `T_i` (`T_simple_action`) and checking it respects the
defining relations (`heckeActionFreeAlgHom_respects_rel`). -/
noncomputable def heckeActionAlgHom :
    HeckeAlgebra W →ₐ[HeckeRing W] Module.End (HeckeRing W) (module_actedOn W) :=
  RingQuot.liftAlgHom (HeckeRing W) ⟨heckeActionFreeAlgHom, heckeActionFreeAlgHom_respects_rel⟩

theorem heckeActionAlgHom_T_simple (i : B W) :
    heckeActionAlgHom (T_simple i) = T_simple_action i := by
  simp [heckeActionAlgHom, T_simple, heckeActionFreeAlgHom, FreeAlgebra.lift_ι_apply]

end ActOnGroupAlgebra

section FreeBasis

variable {W : Type*} [CoxeterGroup W]

/-- The family `{T_w}` is linearly independent over the constant subring `ℤ`.
This follows by applying the `q = 1` specialization: constants embed injectively into
`MonoidAlgebra ℤ W`, and `T_w` maps to the standard group-algebra basis vector. -/
theorem T_intLinearIndependent [Matsumoto (W1 := W)] :
  LinearIndependent ℤ (T (W := W)) := by
  let f : HeckeAlgebra W →ₗ[ℤ] MonoidAlgebra ℤ W :=
    { toFun := qOneAlgHom0 (W := W)
      map_add' := map_add (qOneAlgHom0 (W := W))
      map_smul' := fun n x => by
        simpa only [RingHom.id_apply] using
          (qOneAlgHom0 (W := W) : HeckeAlgebra W →+* MonoidAlgebra ℤ W).map_zsmul n x }
  exact LinearIndependent.of_comp f (by
    simpa [f, Function.comp_def] using qOneAlgHom0_T_linearIndependent (W := W))

/-- The obligation that `{T_w : w ∈ W}`
is linearly independent over `HeckeRing W`
one of the two facts needed to build `basis` via `Module.Basis.mk`. -/
theorem T_linearIndependent [Matsumoto (W1 := W)] :
  LinearIndependent (HeckeRing W) (T (W := W)) :=
  sorry

/-- The obligation that `{T_w : w ∈ W}`
spans `HeckeAlgebra W` over `HeckeRing W`
the other fact needed to build `basis` via `Module.Basis.mk`. -/
theorem T_span : ⊤ ≤ Submodule.span (HeckeRing W) (Set.range (T (W := W))) :=
  sorry

/-- `HeckeAlgebra` is free as a `HeckeRing`-module with basis `{T_w : w ∈ W}`. -/
noncomputable def basis [Matsumoto (W1 := W)] :
  Module.Basis W (HeckeRing W) (HeckeAlgebra W) :=
  Module.Basis.mk T_linearIndependent T_span

theorem basis_apply (w : W) [Matsumoto (W1 := W)] :
  basis w = T w :=
  Module.Basis.mk_apply T_linearIndependent T_span w

end FreeBasis

section BarInvolution

variable {W : Type*} [CoxeterGroup W]

/-- The **bar involution** on `HeckeAlgebra`
The additive ring automorphism
sending `T_w ↦ (T_{w⁻¹})⁻¹`
semilinear over `barScalar` -/
noncomputable def bar :
  HeckeAlgebra W ≃+* HeckeAlgebra W := sorry

private theorem bar_smul (c : HeckeRing W) (x : HeckeAlgebra W) :
  bar (c • x) = star c • bar x := by
  sorry

private theorem bar_T (w : W) :
  bar (T w) * T w⁻¹ = 1 := by
  sorry

private theorem bar_T_involutive (w : W) : bar (bar (T w)) = T w := by
  have h1 := bar_T w
  have h2 := bar_T w⁻¹
  rw [inv_inv] at h2
  have h4 : bar (bar (T w)) * bar (T w⁻¹) = 1 := by
    rw [← map_mul, h1, map_one]
  calc bar (bar (T w))
      = bar (bar (T w)) * 1 := (mul_one _).symm
    _ = bar (bar (T w)) * (bar (T w⁻¹) * T w) := by rw [h2]
    _ = bar (bar (T w)) * bar (T w⁻¹) * T w :=
        (mul_assoc _ _ _).symm
    _ = 1 * T w := by rw [h4]
    _ = T w := one_mul _

/-- Involutivity of `bar` on all of `HeckeAlgebra`
Induct on the standard basis `{T_w}` -/
theorem bar_involutive [Matsumoto (W1 := W)] :
  Function.Involutive (bar (W := W)) := by
  intro x
  rw [← basis.linearCombination_repr x]
  generalize basis.repr x = f
  induction f using Finsupp.induction with
  | zero => simp
  | single_add w c f _hw hc ih =>
    have hsingle : Finsupp.linearCombination (HeckeRing W) basis (Finsupp.single w c + f)
        = c • T w + Finsupp.linearCombination (HeckeRing W) basis f := by
      rw [map_add, Finsupp.linearCombination_single, basis_apply]
    rw [hsingle, map_add, map_add, bar_smul, bar_smul, star_involutive, bar_T_involutive, ih]

end BarInvolution

end Coxeter
